#!/usr/bin/env nbb
;; Standalone nbb port of edn-datomize.cljs (ADR-2607173000 Wave 1).
;; Schema lives at <git-root>/schema.edn (child-repo convention).
;; Superproject uses manifest/edn-datomize.cljs (schema at manifest/schema.edn).
;;
;;   nbb edn-datomize.cljs wrap-map <path> <ns>
;;   nbb edn-datomize.cljs wrap-map-keep-ns <path> <ns>
;;   nbb edn-datomize.cljs adr-dir <dir>
;;   nbb edn-datomize.cljs adr-file <path>
(require '[clojure.edn :as edn]
         '[clojure.string :as str])

(def fs (js/require "node:fs"))
(def path (js/require "node:path"))
(def cp (js/require "node:child_process"))

(defn- sh [& args]
  (let [r (.spawnSync cp (first args) (to-array (rest args)) #js {:encoding "utf8"})]
    {:exit (or (.-status r) 1) :out (or (.-stdout r) "") :err (or (.-stderr r) "")}))

(defn- slurp [f] (.readFileSync fs (str f) "utf8"))
(defn- spit [f s]
  (.mkdirSync fs (.dirname path (str f)) #js {:recursive true})
  (.writeFileSync fs (str f) (str s)))
(defn- exists? [f] (.existsSync fs (str f)))
(defn- file-join [& xs] (apply (.-join path) (map str xs)))

(def root (str/trim (:out (sh "git" "rev-parse" "--show-toplevel"))))
(defn schema-path [] (file-join root "schema.edn"))

(defn slurp-edn [p] (edn/read-string (slurp p)))

(defn already-tx-data? [content]
  (and (vector? content) (seq content) (map? (first content)) (contains? (first content) :db/id)))

(defn classify [v]
  (cond
    (string? v)  {:type :db.type/string  :card :db.cardinality/one}
    (boolean? v) {:type :db.type/boolean :card :db.cardinality/one}
    (integer? v) {:type :db.type/long    :card :db.cardinality/one}
    (double? v)  {:type :db.type/double  :card :db.cardinality/one}
    (keyword? v) {:type :db.type/keyword :card :db.cardinality/one}
    (nil? v)     {:type :db.type/string  :card :db.cardinality/one}
    (and (coll? v) (empty? v)) {:type :db.type/string :card :db.cardinality/many}
    (and (coll? v) (every? string? v))  {:type :db.type/string  :card :db.cardinality/many}
    (and (coll? v) (every? keyword? v)) {:type :db.type/keyword :card :db.cardinality/many}
    (and (coll? v) (every? integer? v)) {:type :db.type/long    :card :db.cardinality/many}
    :else {:type :db.type/string :card :db.cardinality/one :blob true}))

(defn attr-value [v]
  (let [{:keys [blob]} (classify v)]
    (if blob (pr-str v) v)))

(defn namespaced-key [ns-name k]
  (keyword ns-name (name k)))

(defn schema-attrs [content ns-name]
  (into {}
        (for [[k v] content
              :let [{:keys [type card]} (classify v)
                    a (namespaced-key ns-name k)]]
          [a {:db/ident a :db/valueType type :db/cardinality card}])))

(defn schema-attrs-keep-ns [content ns-name]
  (into {}
        (for [[k v] content
              :let [{:keys [type card]} (classify v)
                    a (if (namespace k) k (namespaced-key ns-name k))]]
          [a {:db/ident a :db/valueType type :db/cardinality card}])))

(defn load-schema []
  (let [f (schema-path)]
    (if (exists? f) (edn/read-string (slurp f)) [])))

(defn merge-schema! [new-attrs]
  (let [existing (load-schema)
        by-ident (into {} (map (fn [a] [(:db/ident a) a]) existing))
        merged (vals (merge by-ident new-attrs))]
    (spit (schema-path)
          (str ";; schema.edn — Datomic/Datascript compatible (auto-generated by edn-datomize.cljs)\n"
               (pr-str (vec merged)) "\n"))))

(defn wrap-map! [rel-path ns-name keep-ns?]
  (let [f (if (.isAbsolute path rel-path) rel-path (file-join root rel-path))
        content (slurp-edn f)]
    (when-not (map? content)
      (binding [*out* *err*] (println "not a map:" f))
      (.exit js/process 1))
    (if (already-tx-data? [content])
      (println "already tx-data, skip" f)
      (let [attrs (if keep-ns?
                    (schema-attrs-keep-ns content ns-name)
                    (schema-attrs content ns-name))
            entity (into {:db/id -1}
                         (for [[k v] content]
                           [(if (and keep-ns? (namespace k)) k (namespaced-key ns-name k))
                            (attr-value v)]))]
        (merge-schema! attrs)
        (spit f (str (pr-str [entity]) "\n"))
        (println "wrote" f)))))

(defn- parse-frontmatter [text]
  (if-let [[_ fm body] (re-find #"(?s)^---\n(.*?)\n---\n?(.*)$" text)]
    (let [pairs (for [line (str/split-lines fm)
                      :when (str/includes? line ":")
                      :let [[k & rest] (str/split line #":" 2)]]
                  [(keyword (str/trim k)) (str/trim (str/join ":" rest))])]
      [(into {} pairs) body])
    [{} text]))

(defn adr-file! [rel-path]
  (let [f (if (.isAbsolute path rel-path) rel-path (file-join root rel-path))
        text (slurp f)
        [fm body] (parse-frontmatter text)
        entity (into {:db/id -1
                      :adr/path (str/replace (str f) (str root "/") "")
                      :adr/body body}
                     (for [[k v] fm]
                       [(keyword "adr" (name k)) v]))]
    (merge-schema! (schema-attrs (dissoc entity :db/id) "adr"))
    (let [out (str f ".edn")]
      (spit out (str (pr-str [entity]) "\n"))
      (println "wrote" out))))

(defn adr-dir! [rel]
  (let [d (if (.isAbsolute path rel) rel (file-join root rel))
        files (.readdirSync fs d)]
    (doseq [name files
            :when (or (str/ends-with? name ".md") (str/ends-with? name ".md.edn"))]
      (adr-file! (file-join d name)))))

(let [args (vec *command-line-args*)
      args (if (and (seq args) (str/includes? (str (first args)) "edn-datomize"))
             (subvec args 1) args)
      [cmd a b] args]
  (case cmd
    "wrap-map" (wrap-map! a b false)
    "wrap-map-keep-ns" (wrap-map! a b true)
    "adr-file" (adr-file! a)
    "adr-dir" (adr-dir! a)
    (do (println "usage: edn-datomize.cljs wrap-map|wrap-map-keep-ns|adr-file|adr-dir ...")
        (.exit js/process 2))))
